# Generated by Django 4.1.2 on 2023-04-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='age',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True),
        ),
    ]
