# Generated by Django 4.1.2 on 2023-04-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_myuser_age_alter_myuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='../media/avatars/'),
        ),
    ]
