# Generated by Django 4.1.2 on 2023-04-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_myuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='body_shape',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='skin_tone',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
