# Generated by Django 4.1.2 on 2023-04-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_myuser_gender_alter_myuser_body_shape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='../media/images/'),
        ),
    ]
