# Generated by Django 4.1.2 on 2023-04-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_myuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='age',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
